#!/bin/bash

# Change the IP address of localhost to 127.0.0.2
sudo sed -i 's/127\.0\.0\.1/127\.0\.0\.2/' /etc/hosts

# Set Google DNS servers as the primary DNS servers
sudo cp /etc/resolv.conf /etc/resolv.conf.bak
sudo echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
sudo echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf > /dev/null
```
